// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JNlLN-ekRIp4L8L5EBs1c4E7RxiARN8',
    appId: '1:461169639709:android:d38e17cf4d3eb3f70e21f4',
    messagingSenderId: '461169639709',
    projectId: 'revo-theatre-management',
    storageBucket: 'revo-theatre-management.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVaA9mmmxXTJ4Oui8uWny13Wp-bCxD2b0',
    appId: '1:461169639709:web:2da59bf5df27fd0b0e21f4',
    messagingSenderId: '461169639709',
    projectId: 'revo-theatre-management',
    authDomain: 'revo-theatre-management.firebaseapp.com',
    storageBucket: 'revo-theatre-management.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVaA9mmmxXTJ4Oui8uWny13Wp-bCxD2b0',
    appId: '1:461169639709:web:2da59bf5df27fd0b0e21f4',
    messagingSenderId: '461169639709',
    projectId: 'revo-theatre-management',
    authDomain: 'revo-theatre-management.firebaseapp.com',
    storageBucket: 'revo-theatre-management.firebasestorage.app',
  );
}
